
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  frontend:
    image: node:20
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend/admin-panel:/app
      - /app/node_modules
    environment:
      - PORT=3000
    ports:
      - "3000:3001"  # porta padrão do react-scripts é 3000
    command: sh -c "npm install && npm start -- --host 0.0.0.0"
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
